// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYgK5n-5FEGHHHAZwOmwqKPcbnB8ZW0K8',
    appId: '1:831661833392:web:dfa4e1893289a28b3f4f75',
    messagingSenderId: '831661833392',
    projectId: 'notesapp-331ca',
    authDomain: 'notesapp-331ca.firebaseapp.com',
    storageBucket: 'notesapp-331ca.appspot.com',
    measurementId: 'G-GQG5GK0KMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT3aYqo_wmFWElFof_XAdxtuR97L5cqNQ',
    appId: '1:831661833392:android:b3e7bec386b3f1093f4f75',
    messagingSenderId: '831661833392',
    projectId: 'notesapp-331ca',
    storageBucket: 'notesapp-331ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-y1B4vuJlG88iaxi6CFJMPe-DfziaALw',
    appId: '1:831661833392:ios:2964544895144fff3f4f75',
    messagingSenderId: '831661833392',
    projectId: 'notesapp-331ca',
    storageBucket: 'notesapp-331ca.appspot.com',
    iosBundleId: 'com.example.taskManagement',
  );

}